services:
  backend:
    build:
      context: ../advanced-hello-world-be
    image: advanced-hello-world-be:dev

  migrate:
    build:
      context: ../advanced-hello-world-be
    image: advanced-hello-world-be:dev

  frontend:
    build:
      context: ../advanced-hello-world-fe
    image: advanced-hello-world-fe:dev
